apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-to-brokers-submariner-crd
rules:
  - apiGroups: ["submariner.io"]
    resources: ["brokers"]
    verbs: ["create", "get", "update"]