apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acm-submariner
rules:
- apiGroups: [""]
  resources: ["configmaps","namespaces", "serviceaccounts", "secrets", "pods"]
  verbs: ["create", "get", "list", "update", "watch", "patch", "delete"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings", "rolebindings"]
  verbs: ["create", "get", "list", "update", "watch", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "roles"]
  verbs: ["create", "get", "list", "update", "watch", "patch", "delete", "escalate", "bind"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "update", "watch", "patch", "delete"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters","managedclustersets"]
  verbs: ["get", "list", "watch","update", "patch"]
- apiGroups: ["work.open-cluster-management.io"]
  resources: ["manifestworks"]
  verbs: ["get", "list", "watch","create", "update", "patch", "delete"]
- apiGroups: ["config.openshift.io"]
  resources: ["infrastructures","infrastructures/status"]
  verbs: ["get"]
